version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocktaildb
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ]
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    restart: on-failure
    #ports:
      #- "5000:5000"
    depends_on:
      db:
        condition: service_healthy
